---
- hosts: localhost
  become: true
  tasks:
    # https://kubernetes.io/ja/docs/setup/production-environment/container-runtimes/
    - name: cp k8s-modules-load conf
      copy:
        src: ./configs/k8s-modules-load.conf
        dest: /etc/modules-load.d/k8s-modules-load.conf
    - name: apply modules-load
      shell: | 
        modprobe overlay
        modprobe br_netfilter
    - name: cp k8s-sysctl conf
      copy:
        src: ./configs/k8s-sysctl.conf
        dest: /etc/sysctl.d/k8s-sysctl.conf
    - name: apply sysctl
      shell: | 
        sudo sysctl --system
    - name: confirmation
      shell: | 
        lsmod | grep br_netfilter
        lsmod | grep overlay
        sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward
    - name: Install Docker public signing key
      shell: curl -sSL https://download.docker.com/linux/debian/gpg | gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
    - name: Add the Docker apt repository
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable
        create: yes
    - name: install containerd
      apt: 
        name: containerd
    - name: cp containerd config.toml
      copy:
        src: ./configs/config.toml
        dest: /etc/containerd/config.toml
    - name: restart containerd
      shell: systemctl restart containerd
    - name: Install k8s public signing key
      shell: curl -fsSL https://dl.k8s.io/apt/doc/apt-key.gpg | gpg --dearmor --yes -o /usr/share/keyrings/kubernetes-archive-keyring.gpg
    - name: Add the k8s apt repository
      lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
        create: yes
    - name: install k8s
      apt:
        update_cache: yes
        name:
          - kubelet
          - kubeadm
          - kubectl
    