network:
  version: 2
  renderer: NetworkManager
  wifis:
    wlan0:
      dhcp4: false
      dhcp6: false
      addresses: [192.168.1.50/24]
      gateway4: 192.168.1.1
      nameservers:
        addresses: [192.168.1.1, 1.1.1.1, 8.8.8.8, 8.8.4.4]
